import chalk from 'chalk';
import type { HanTask, MachineConfig, ProjectConfig } from '../types.js';
import type { ExecutorResult } from './index.js';
import { resolveBrain } from '../brains/router.js';
import { createWorkspace, commitAndPush, createPR } from './workspace.js';

const SYSTEM_PROMPT = `You are Han AI — an autonomous dev agent working inside a git repository.
Your job is to complete the given task by reading, editing, and creating files.
- Use the available tools (Read, Write, Edit, Bash) to explore and modify the codebase.
- Be precise. Only change what is necessary for the task.
- Do not add unnecessary comments or refactors outside the task scope.
- When done, output a short summary of what you changed.`;

export async function devExecutor(
  task: HanTask,
  config: MachineConfig,
  project: ProjectConfig,
): Promise<ExecutorResult> {
  if (project.github_repo === undefined) {
    throw new Error(`Project "${project.project_id}" has no github_repo configured`);
  }

  console.log(chalk.gray(`   cloning ${project.github_repo}...`));
  const ws = createWorkspace(project.github_repo, task.id);

  try {
    const brain = resolveBrain(config, 'dev');

    const userPrompt = [
      `Task: ${task.title}`,
      task.context !== undefined ? `\nContext:\n${task.context}` : '',
      `\nRepository has been cloned to your working directory.`,
      `Complete the task, then output a summary of changes made.`,
    ].join('');

    console.log(chalk.gray(`   running brain: ${config.brain.dev ?? config.brain.default}...`));
    const result = await brain.run({
      systemPrompt: SYSTEM_PROMPT,
      userPrompt,
      workspaceDir: ws.dir,
    });

    const commitMsg = `han: ${task.title}`;
    const hasChanges = commitAndPush(ws, commitMsg);

    if (!hasChanges) {
      console.log(chalk.yellow('   no file changes detected — skipping PR'));
      return { brainUsed: result.brainUsed };
    }

    console.log(chalk.gray(`   creating PR on branch ${ws.branch}...`));
    const prBody = [
      result.text.slice(0, 1000),
      `\n---\n🤖 Generated by Han AI | task: ${task.id}`,
    ].join('');

    const prUrl = createPR(ws, task.title, prBody);
    console.log(chalk.green(`   PR: ${prUrl}`));

    return { outputUrl: prUrl, brainUsed: result.brainUsed };
  } finally {
    ws.cleanup();
  }
}
